test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: eloquent_feed_development
  host: localhost
  pool: 5
  username: eloquent_feed
  password: password
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: eloquent_feed_production
  host: localhost
  pool: 5
  username: eloquent_feed
  password: password
  timeout: 5000
